name: Auto Multiple Pull Requests

on:
  workflow_dispatch:
    inputs:
      pr_count:
        description: 'Jumlah Pull Request yang akan dibuat'
        required: true
        default: '5'
      commit_message:
        description: 'Pesan commit'
        required: true
        default: 'Auto commit for PR'
      branch_name:
        description: 'Nama branch yang ingin di-PR'
        required: true
        default: 'test'
      base_branch:
        description: 'Branch target PR (misalnya: main atau develop)'
        required: true
        default: 'main'

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Hitung dan Buat Pull Request
      run: |
        pr_count="${{ github.event.inputs.pr_count }}"
        branch_name="${{ github.event.inputs.branch_name }}"
        base_branch="${{ github.event.inputs.base_branch }}"
        commit_message="${{ github.event.inputs.commit_message }}"

        for ((i=1;i<=pr_count;i++)); do
          # Buat branch baru dari feature-branch untuk setiap PR
          new_branch="${branch_name}_pr_$i"
          git checkout -b "$new_branch"
          
          # Buat perubahan atau tambahkan commit jika perlu
          echo "Auto-update for PR $i" >> pr_log.txt
          git add pr_log.txt
          git commit -m "$commit_message for PR $i"
          
          # Push ke remote
          git push origin "$new_branch"

          # Gunakan GitHub API untuk membuat Pull Request
          gh pr create --base "$base_branch" --head "$new_branch" --title "Auto PR $i" --body "This is automatically created PR number $i."
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token untuk autentikasi GitHub CLI
